oléHotels/Models/Client.cs
using System.Collections.Generic;

namespace OleHotels.Models
{
    public class Client : User
    {
        public int ClientId { get; set; }
        public int CardId { get; set; }
        public bool IsCheckedIn { get; set; }

        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual Card Card { get; set; }

    }
}

oléHotels/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace OleHotels.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        public string Username { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

oléHotels/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OleHotels.Models;
using OleHotels.ViewModels;
using Microsoft.AspNetCore.Http;

namespace OleHotels.Controllers
{
    public class ClientController : Controller
    {
        private const string sessionKey = "client_login";
        private readonly IClientRepository _clientRepository;
        public ClientController(IClientRepository clientRepository)
        {
            _clientRepository = clientRepository;
        }

        public IActionResult Login()
        {
            var model = new ClientLoginViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Login(ClientLoginViewModel model)
        {
            if (ModelState.IsValid)
            {

                Client client = _clientRepository.Login(model.Email, model.Password);
                if (client == null)
                {
                    ModelState.AddModelError("Password", "Username or password are not valid");
                }
                else
                {
                    HttpContext.Session.SetString(sessionKey, client.ClientId.ToString());
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(model);
        }

        public IActionResult SignUp()
        {
            var model = new Client();
            return View(model);
        }

        [HttpPost]
        public IActionResult SignUp(Client model)
        {
            if (ModelState.IsValid)
            {
                var newClient = _clientRepository.Create(model);
                if (newClient != null && newClient.ClientId > 0)
                {
                    HttpContext.Session.SetString(sessionKey, newClient.ClientId.ToString());
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("Firstname", "Error creating the user. Please Contact Support.");
                }
            }
            return View();
        }

    }
}

oléHotels/Views/Client/Login.cshtml
@model ClientLoginViewModel
@{
    ViewData["Title"] = "Customer Login";
}
<div class="row">
    <div class="col">
        <img src="/images/login-background.png" class="img-fluid"/>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="modalLogin" tabindex="-1" role="dialog" aria-labelledby="modelLogin" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
          <div class="row">
              <div class="col">
                  <div class="text-center">
                      <img src="/images/logo-home.png" width="200" height="200" class="border-0 img-thumbnail" alt="..." />
                  </div>
                  
              </div>
          </div>
          <div class="row">
              <div class="col">
                  <div class="text-center text-uppercase font-weight-bold">Login</div>
              </div>
          </div>
            <form asp-controller="Client" asp-action="Login" method="post">
                <div class="form-group">
                        <input asp-for="Email" placeholder="Email" class="form-control border-bottom" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="Password" placeholder="password" class="form-control border-bottom" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group text-center">
                    <p>New customer? <a asp-controller="Client" asp-action="SignUp">Sign up</a>.</p>        
                </div>
                <div class="form-group text-center">
                        <button type="button" class="btn btn-secondary rounded-pill" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary rounded-pill site-bg-color">Login</button>
                </div>
            </form>
      </div>
    </div>
  </div>
</div>

@section Scripts
{
    <script>
    $(function(){
        $('#modalLogin').modal('show')
 
        $('#modalLogin').on('hidden.bs.modal', function (e) {
            window.location = "/Home/Index";
        }); 
    });  
    </script>  
}

oléHotels/Views/Client/SignUp.cshtml
@model Client
@{
    ViewData["Title"] = "Customer Login";
}
<div class="row">
    <div class="col">
        <img src="/images/login-background.png" class="img-fluid"/>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="modalLogin" tabindex="-1" role="dialog" aria-labelledby="modelLogin" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
          <div class="row">
              <div class="col">
                  <div class="text-center">
                      <img src="/images/logo-home.png" width="200" height="200" class="border-0 img-thumbnail" alt="..." />
                  </div>
                  
              </div>
          </div>
          <div class="row">
              <div class="col">
                  <div class="text-center text-uppercase font-weight-bold">Sign Up</div>
              </div>
          </div>
            <form asp-controller="Client" asp-action="SignUp" method="post">
                <div class="form-group">
                    <input asp-for="Username" placeholder="username" class="form-control border-bottom" />
                    <span asp-validation-for="Username" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="Password" placeholder="password" class="form-control border-bottom" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="FirstName" placeholder="First Name" class="form-control border-bottom" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="LastName" placeholder="Last Name" class="form-control border-bottom" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="Email" placeholder="Email" class="form-control border-bottom" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="Phone" placeholder="Phone" class="form-control border-bottom" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                
                <div class="form-group text-center">
                        <button type="button" class="btn btn-secondary rounded-pill" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary rounded-pill site-bg-color">Sign Up</button>
                </div>
            </form>
      </div>
    </div>
  </div>
</div>

@section Scripts
{
    <script>
    $(function(){
        $('#modalLogin').modal('show')
 
        $('#modalLogin').on('hidden.bs.modal', function (e) {
            window.location = "/Home/Index";
        }); 
    });  
    </script>  
}